[supervisord]
nodaemon=true
user=root
logfile=/dev/null
logfile_maxbytes=0
pidfile=/run/sideloop-supervisord.pid
childlogdir=/tmp

[unix_http_server]
file=/run/sideloop-supervisor.sock

[rpcinterface:supervisor]
supervisor.rpcinterface_factory=supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///run/sideloop-supervisor.sock

[program:anisette]
command=/usr/local/bin/anisette-v3-server --host 127.0.0.1 --adi-path %(ENV_DATA_DIR)s/anisette
directory=%(ENV_DATA_DIR)s/anisette
user=Alcoholic
environment=HOME="/home/Alcoholic",RUNTIME_DIRECTORY="%(ENV_DATA_DIR)s/anisette/runtime"
priority=10
autostart=true
autorestart=true
startsecs=2
startretries=5
stopasgroup=true
killasgroup=true
stopwaitsecs=20
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0

[program:sideloop]
command=/usr/local/bin/container-run-sideloop.sh
directory=%(ENV_DATA_DIR)s
priority=20
autostart=true
autorestart=true
startsecs=2
startretries=5
stopasgroup=true
killasgroup=true
stopwaitsecs=20
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0
